#!/usr/bin/env node
/**
 * init-status.mjs — Bootstraps i18n-status files for existing locales.
 *
 * For each extension, looks at the source (en) messages and initializes
 * the status file for all non-source locales. As requested, all non-English
 * translations are marked as AI-generated by default, and untranslated keys
 * are initialized to a 'missing' state.
 */

import {
	hashMessage,
	listExtensions,
	listLocales,
	loadMessages,
	loadStatus,
	SOURCE_LOCALE,
	saveStatus,
} from "./utils.mjs";

for (const ext of listExtensions()) {
	const source = loadMessages(ext, SOURCE_LOCALE);
	if (!source) continue;

	const locales = listLocales(ext).filter((l) => l !== SOURCE_LOCALE);

	for (const locale of locales) {
		const target = loadMessages(ext, locale) || {};
		const status = loadStatus(ext, locale);

		for (const [key, entry] of Object.entries(source)) {
			// Mark existing translations as ai-draft (AI generated)
			// and non-existing as missing (unknown/untranslated)
			status[key] = {
				status: target[key] ? "ai-draft" : "missing",
				source_hash: hashMessage(entry),
			};
		}

		// Clean up keys in status that no longer exist in source
		for (const key of Object.keys(status)) {
			if (!source[key]) {
				delete status[key];
			}
		}

		saveStatus(ext, locale, status);
		console.log(
			`[${ext}/${locale}] Status file synced: marked all target keys as ai-draft/missing.`,
		);
	}
}
